server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users,/users/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=orders,/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://3.110.128.197:8761/eureka